version: 0.2

phases:
  install:
    runtime-versions:
      docker: 24  # Optional if the default version works for your project
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      # Log in to Docker Hub securely using AWS Secrets Manager or environment variables
      - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
      - export IMAGE_NAME=ahmeddevops85/awsdemp  # Docker image name

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_NAME:latest .  # Build the Docker image using the IMAGE_NAME variable

  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push $IMAGE_NAME:latest  # Push the image to Docker Hub

# If you're not using artifacts in the CI/CD pipeline, you can omit this section
artifacts:
  files:
    - '**/*'  # Optional: Only use if you want to store additional build artifacts


